spring.datasource.url=jdbc:mysql://localhost:3306/tmsdb?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.connection.init_sqls=SET FOREIGN_KEY_CHECKS=0
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false



# Enable GraphQL logs
logging.level.org.springframework.graphql=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.boot.autoconfigure.graphql=DEBUG

spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql


spring.graphql.schema.locations=classpath:schema.graphqls
spring.main.lazy-initialization=false


